---
# Set up systemd timers for automatic syncing
- name: Create drift-management directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_user_dir }}/.local/share/drift-management"
    - "{{ ansible_user_dir }}/.local/share/drift-management/reports"
    - "{{ ansible_user_dir }}/.config/systemd/user"

- name: Install content-sync systemd service
  ansible.builtin.template:
    src: content-sync.service.j2
    dest: "{{ ansible_user_dir }}/.config/systemd/user/content-sync.service"
    mode: '0644'

- name: Install content-sync systemd timer
  ansible.builtin.template:
    src: content-sync.timer.j2
    dest: "{{ ansible_user_dir }}/.config/systemd/user/content-sync.timer"
    mode: '0644'

- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Enable and start content-sync timer
  ansible.builtin.systemd:
    name: content-sync.timer
    enabled: true
    state: started
    scope: user
  when: enable_timer | default(true)

